use astra_derive::{Astra, AstraBook};
use astra_formats::Sheet;

#[derive(AstraBook)]
pub struct CalculatorBook {
    pub common_functions: Sheet<Vec<CalculatorCommon>>,
    pub exp_table: Sheet<Vec<ExpTableEntry>>,
}

#[derive(Debug, Default, Clone, Astra)]
pub struct CalculatorCommon {
    #[astra(key = "@Name")]
    pub name: String,
    #[astra(key = "@Condition")]
    pub condition: Vec<String>,
    #[astra(key = "@Function")]
    pub function: Vec<String>,
}

#[derive(Debug, Default, Clone, Astra)]
pub struct ExpTableEntry {
    #[astra(key = "@Name")]
    pub name: String,
    #[astra(key = "@M39")]
    pub m_39: Option<i32>,
    #[astra(key = "@M38")]
    pub m_38: Option<i32>,
    #[astra(key = "@M37")]
    pub m_37: Option<i32>,
    #[astra(key = "@M36")]
    pub m_36: Option<i32>,
    #[astra(key = "@M35")]
    pub m_35: Option<i32>,
    #[astra(key = "@M34")]
    pub m_34: Option<i32>,
    #[astra(key = "@M33")]
    pub m_33: Option<i32>,
    #[astra(key = "@M32")]
    pub m_32: Option<i32>,
    #[astra(key = "@M31")]
    pub m_31: Option<i32>,
    #[astra(key = "@M30")]
    pub m_30: Option<i32>,
    #[astra(key = "@M29")]
    pub m_29: Option<i32>,
    #[astra(key = "@M28")]
    pub m_28: Option<i32>,
    #[astra(key = "@M27")]
    pub m_27: Option<i32>,
    #[astra(key = "@M26")]
    pub m_26: Option<i32>,
    #[astra(key = "@M25")]
    pub m_25: Option<i32>,
    #[astra(key = "@M24")]
    pub m_24: Option<i32>,
    #[astra(key = "@M23")]
    pub m_23: Option<i32>,
    #[astra(key = "@M22")]
    pub m_22: Option<i32>,
    #[astra(key = "@M21")]
    pub m_21: Option<i32>,
    #[astra(key = "@M20")]
    pub m_20: Option<i32>,
    #[astra(key = "@M19")]
    pub m_19: Option<i32>,
    #[astra(key = "@M18")]
    pub m_18: Option<i32>,
    #[astra(key = "@M17")]
    pub m_17: Option<i32>,
    #[astra(key = "@M16")]
    pub m_16: Option<i32>,
    #[astra(key = "@M15")]
    pub m_15: Option<i32>,
    #[astra(key = "@M14")]
    pub m_14: Option<i32>,
    #[astra(key = "@M13")]
    pub m_13: Option<i32>,
    #[astra(key = "@M12")]
    pub m_12: Option<i32>,
    #[astra(key = "@M11")]
    pub m_11: Option<i32>,
    #[astra(key = "@M10")]
    pub m_10: Option<i32>,
    #[astra(key = "@M09")]
    pub m_09: Option<i32>,
    #[astra(key = "@M08")]
    pub m_08: Option<i32>,
    #[astra(key = "@M07")]
    pub m_07: Option<i32>,
    #[astra(key = "@M06")]
    pub m_06: Option<i32>,
    #[astra(key = "@M05")]
    pub m_05: Option<i32>,
    #[astra(key = "@M04")]
    pub m_04: Option<i32>,
    #[astra(key = "@M03")]
    pub m_03: Option<i32>,
    #[astra(key = "@M02")]
    pub m_02: Option<i32>,
    #[astra(key = "@M01")]
    pub m_01: Option<i32>,
    #[astra(key = "@N00")]
    pub n_00: Option<i32>,
    #[astra(key = "@P01")]
    pub p_01: Option<i32>,
    #[astra(key = "@P02")]
    pub p_02: Option<i32>,
    #[astra(key = "@P03")]
    pub p_03: Option<i32>,
    #[astra(key = "@P04")]
    pub p_04: Option<i32>,
    #[astra(key = "@P05")]
    pub p_05: Option<i32>,
    #[astra(key = "@P06")]
    pub p_06: Option<i32>,
    #[astra(key = "@P07")]
    pub p_07: Option<i32>,
    #[astra(key = "@P08")]
    pub p_08: Option<i32>,
    #[astra(key = "@P09")]
    pub p_09: Option<i32>,
    #[astra(key = "@P10")]
    pub p_10: Option<i32>,
    #[astra(key = "@P11")]
    pub p_11: Option<i32>,
    #[astra(key = "@P12")]
    pub p_12: Option<i32>,
    #[astra(key = "@P13")]
    pub p_13: Option<i32>,
    #[astra(key = "@P14")]
    pub p_14: Option<i32>,
    #[astra(key = "@P15")]
    pub p_15: Option<i32>,
    #[astra(key = "@P16")]
    pub p_16: Option<i32>,
    #[astra(key = "@P17")]
    pub p_17: Option<i32>,
    #[astra(key = "@P18")]
    pub p_18: Option<i32>,
    #[astra(key = "@P19")]
    pub p_19: Option<i32>,
    #[astra(key = "@P20")]
    pub p_20: Option<i32>,
    #[astra(key = "@P21")]
    pub p_21: Option<i32>,
    #[astra(key = "@P22")]
    pub p_22: Option<i32>,
    #[astra(key = "@P23")]
    pub p_23: Option<i32>,
    #[astra(key = "@P24")]
    pub p_24: Option<i32>,
    #[astra(key = "@P25")]
    pub p_25: Option<i32>,
    #[astra(key = "@P26")]
    pub p_26: Option<i32>,
    #[astra(key = "@P27")]
    pub p_27: Option<i32>,
    #[astra(key = "@P28")]
    pub p_28: Option<i32>,
    #[astra(key = "@P29")]
    pub p_29: Option<i32>,
    #[astra(key = "@P30")]
    pub p_30: Option<i32>,
    #[astra(key = "@P31")]
    pub p_31: Option<i32>,
    #[astra(key = "@P32")]
    pub p_32: Option<i32>,
    #[astra(key = "@P33")]
    pub p_33: Option<i32>,
    #[astra(key = "@P34")]
    pub p_34: Option<i32>,
    #[astra(key = "@P35")]
    pub p_35: Option<i32>,
    #[astra(key = "@P36")]
    pub p_36: Option<i32>,
    #[astra(key = "@P37")]
    pub p_37: Option<i32>,
    #[astra(key = "@P38")]
    pub p_38: Option<i32>,
    #[astra(key = "@P39")]
    pub p_39: Option<i32>,
    #[astra(key = "@P40")]
    pub p_40: Option<i32>,
}
