use astra_derive::{Astra, AstraBook};
use astra_formats::indexmap::IndexMap;
use astra_formats::Sheet;

#[derive(AstraBook)]
pub struct PersonBook {
    pub persons: Sheet<IndexMap<String, Person>>,
}

#[derive(Astra, Debug, Default, Clone)]
pub struct Person {
    #[astra(key = "@Out")]
    pub out: String,
    #[astra(key = "@Pid", id)]
    pub pid: String,
    #[astra(key = "@Fid")]
    pub fid: String,
    #[astra(key = "@Name")]
    pub name: String,
    #[astra(key = "@Jid")]
    pub jid: String,
    #[astra(key = "@Aid")]
    pub aid: String,
    #[astra(key = "@Help")]
    pub help: String,
    #[astra(key = "@Die")]
    pub die: String,
    #[astra(key = "@Belong")]
    pub belong: String,
    #[astra(key = "@UnitIconID")]
    pub unit_icon_id: String,
    #[astra(key = "@Age")]
    pub age: Option<i16>,
    #[astra(key = "@Gender")]
    pub gender: Option<i8>,
    #[astra(key = "@BirthMonth")]
    pub birth_month: Option<u8>,
    #[astra(key = "@BirthDay")]
    pub birth_day: Option<u8>,
    #[astra(key = "@Level")]
    pub level: Option<u8>,
    #[astra(key = "@InternalLevel")]
    pub internal_level: Option<i8>,
    #[astra(key = "@AutoGrowOffsetN")]
    pub auto_grow_offset_n: Option<i8>,
    #[astra(key = "@AutoGrowOffsetH")]
    pub auto_grow_offset_h: Option<i8>,
    #[astra(key = "@AutoGrowOffsetL")]
    pub auto_grow_offset_l: Option<i8>,
    #[astra(key = "@AssetForce")]
    pub asset_force: Option<i8>,
    #[astra(key = "@SupportCategory")]
    pub support_category: String,
    #[astra(key = "@SkillPoint")]
    pub skill_point: Option<i32>,
    #[astra(key = "@BmapSize")]
    pub bmap_size: Option<u8>,
    #[astra(key = "@Flag")]
    pub flag: Option<u8>,
    #[astra(key = "@Aptitude")]
    pub aptitude: Option<i32>,
    #[astra(key = "@SubAptitude")]
    pub sub_aptitude: Option<i32>,
    #[astra(key = "@OffsetN.Hp")]
    pub offset_n_hp: Option<i8>,
    #[astra(key = "@OffsetN.Str")]
    pub offset_n_str: Option<i8>,
    #[astra(key = "@OffsetN.Tech")]
    pub offset_n_tech: Option<i8>,
    #[astra(key = "@OffsetN.Quick")]
    pub offset_n_quick: Option<i8>,
    #[astra(key = "@OffsetN.Luck")]
    pub offset_n_luck: Option<i8>,
    #[astra(key = "@OffsetN.Def")]
    pub offset_n_def: Option<i8>,
    #[astra(key = "@OffsetN.Magic")]
    pub offset_n_magic: Option<i8>,
    #[astra(key = "@OffsetN.Mdef")]
    pub offset_n_mdef: Option<i8>,
    #[astra(key = "@OffsetN.Phys")]
    pub offset_n_phys: Option<i8>,
    #[astra(key = "@OffsetN.Sight")]
    pub offset_n_sight: Option<i8>,
    #[astra(key = "@OffsetN.Move")]
    pub offset_n_move: Option<i8>,
    #[astra(key = "@OffsetH.Hp")]
    pub offset_h_hp: Option<i8>,
    #[astra(key = "@OffsetH.Str")]
    pub offset_h_str: Option<i8>,
    #[astra(key = "@OffsetH.Tech")]
    pub offset_h_tech: Option<i8>,
    #[astra(key = "@OffsetH.Quick")]
    pub offset_h_quick: Option<i8>,
    #[astra(key = "@OffsetH.Luck")]
    pub offset_h_luck: Option<i8>,
    #[astra(key = "@OffsetH.Def")]
    pub offset_h_def: Option<i8>,
    #[astra(key = "@OffsetH.Magic")]
    pub offset_h_magic: Option<i8>,
    #[astra(key = "@OffsetH.Mdef")]
    pub offset_h_mdef: Option<i8>,
    #[astra(key = "@OffsetH.Phys")]
    pub offset_h_phys: Option<i8>,
    #[astra(key = "@OffsetH.Sight")]
    pub offset_h_sight: Option<i8>,
    #[astra(key = "@OffsetH.Move")]
    pub offset_h_move: Option<i8>,
    #[astra(key = "@OffsetL.Hp")]
    pub offset_l_hp: Option<i8>,
    #[astra(key = "@OffsetL.Str")]
    pub offset_l_str: Option<i8>,
    #[astra(key = "@OffsetL.Tech")]
    pub offset_l_tech: Option<i8>,
    #[astra(key = "@OffsetL.Quick")]
    pub offset_l_quick: Option<i8>,
    #[astra(key = "@OffsetL.Luck")]
    pub offset_l_luck: Option<i8>,
    #[astra(key = "@OffsetL.Def")]
    pub offset_l_def: Option<i8>,
    #[astra(key = "@OffsetL.Magic")]
    pub offset_l_magic: Option<i8>,
    #[astra(key = "@OffsetL.Mdef")]
    pub offset_l_mdef: Option<i8>,
    #[astra(key = "@OffsetL.Phys")]
    pub offset_l_phys: Option<i8>,
    #[astra(key = "@OffsetL.Sight")]
    pub offset_l_sight: Option<i8>,
    #[astra(key = "@OffsetL.Move")]
    pub offset_l_move: Option<i8>,
    #[astra(key = "@Limit.Hp")]
    pub limit_hp: Option<i8>,
    #[astra(key = "@Limit.Str")]
    pub limit_str: Option<i8>,
    #[astra(key = "@Limit.Tech")]
    pub limit_tech: Option<i8>,
    #[astra(key = "@Limit.Quick")]
    pub limit_quick: Option<i8>,
    #[astra(key = "@Limit.Luck")]
    pub limit_luck: Option<i8>,
    #[astra(key = "@Limit.Def")]
    pub limit_def: Option<i8>,
    #[astra(key = "@Limit.Magic")]
    pub limit_magic: Option<i8>,
    #[astra(key = "@Limit.Mdef")]
    pub limit_mdef: Option<i8>,
    #[astra(key = "@Limit.Phys")]
    pub limit_phys: Option<i8>,
    #[astra(key = "@Limit.Sight")]
    pub limit_sight: Option<i8>,
    #[astra(key = "@Limit.Move")]
    pub limit_move: Option<i8>,
    #[astra(key = "@Grow.Hp")]
    pub grow_hp: Option<u8>,
    #[astra(key = "@Grow.Str")]
    pub grow_str: Option<u8>,
    #[astra(key = "@Grow.Tech")]
    pub grow_tech: Option<u8>,
    #[astra(key = "@Grow.Quick")]
    pub grow_quick: Option<u8>,
    #[astra(key = "@Grow.Luck")]
    pub grow_luck: Option<u8>,
    #[astra(key = "@Grow.Def")]
    pub grow_def: Option<u8>,
    #[astra(key = "@Grow.Magic")]
    pub grow_magic: Option<u8>,
    #[astra(key = "@Grow.Mdef")]
    pub grow_mdef: Option<u8>,
    #[astra(key = "@Grow.Phys")]
    pub grow_phys: Option<u8>,
    #[astra(key = "@Grow.Sight")]
    pub grow_sight: Option<u8>,
    #[astra(key = "@Grow.Move")]
    pub grow_move: Option<u8>,
    #[astra(key = "@Items")]
    pub items: Vec<String>,
    #[astra(key = "@DropItem")]
    pub drop_item: String,
    #[astra(key = "@DropRatio")]
    pub drop_ratio: Option<f32>,
    #[astra(key = "@Attrs")]
    pub attrs: Option<i32>,
    #[astra(key = "@CommonSids")]
    pub common_sids: Vec<String>,
    #[astra(key = "@NormalSids")]
    pub normal_sids: Vec<String>,
    #[astra(key = "@HardSids")]
    pub hard_sids: Vec<String>,
    #[astra(key = "@LunaticSids")]
    pub lunatic_sids: Vec<String>,
    #[astra(key = "@EngageSid")]
    pub engage_sid: String,
    #[astra(key = "@TalkPauseDelayMin")]
    pub talk_pause_delay_min: Option<f32>,
    #[astra(key = "@TalkPauseDelayMax")]
    pub talk_pause_delay_max: Option<f32>,
    #[astra(key = "@TalkPauseSpeed")]
    pub talk_pause_speed: Option<f32>,
    #[astra(key = "@CombatBgm")]
    pub combat_bgm: String,
    #[astra(key = "@ExistDieCid")]
    pub exist_die_cid: String,
    #[astra(key = "@ExistDieTiming")]
    pub exist_die_timing: Option<i8>,
    #[astra(key = "@Hometown")]
    pub hometown: Option<i8>,
    #[astra(key = "@NetRankingIndex")]
    pub net_ranking_index: Option<u8>,
    #[astra(key = "@NotLvUpTalkPids")]
    pub not_lv_up_talk_pids: Vec<String>,
    #[astra(key = "@SummonColor")]
    pub summon_color: Option<i8>,
    #[astra(key = "@SummonRank")]
    pub summon_rank: Option<i8>,
    #[astra(key = "@SummonRate")]
    pub summon_rate: Option<i32>,
    #[astra(key = "@SummonGod")]
    pub summon_god: String,
}